### ISSUE TITLE
Matplotlib name error with NavigationToolbar2TkAgg

### ISSUE THREAD

**Issue by easyXAFS** [Dih5/xpecgen#19]
Running with Matplotlib version 3.2.0.

Get the following error when trying to launch `xpecgen` gui.

```python
(base) C:\Users\easyXAFS>xpecgen
Traceback (most recent call last):
  File "c:\tools\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\tools\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\Anaconda3\Scripts\xpecgen.exe\__main__.py", line 4, in <module>
  File "c:\tools\anaconda3\lib\site-packages\xpecgen\xpecgenGUI.py", line 13, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg' (c:\tools\anaconda3\lib\site-packages\matplotlib\backends\backend_tkagg.py)
```

Seems to be a name change on the part of matplotlib: `NavigationToolbar2TkAgg` -> `NavigationToolbar2Tk`
https://stackoverflow.com/questions/50330320/what-to-use-instead-of-navigationtoolbar2tkagg

I can submit a PR changing the names if that would be helpful.

**Comment by Dih5** [comment]
Thank for the issue. I updated the API for modern matplotlib in b751995051787f91bd0ae3d82d4bb33e4f8c8b8c. However, I'm experiencing this open matplotlib bug in my computer when I run the new code:
https://github.com/matplotlib/matplotlib/issues/12074

Hence, I will not update the main branch for the moment. Given that matplotlib issue dates from 2018, I think the best solution could be to use an older version of matplotlib (possibly in a virtualenv).

**Comment by ericpace** [comment]
Hi, just experienced the same NavigationToolbar2TkAgg error. Is there a matplotlib version that you would suggest installing?  I tried installing v2.1.2 (since NavigationToolbar2TkAgg was deprecated as of 2.2) but ran into errors during the install. Probably a conflict with other packages or the Python version I tried (v3.10). 

Since you have suggested a virtualenv dedicated for this tool, could list the required Python and package version numbers that you know work?

Thank you.

**Comment by fleusium** [comment]
I ran into this on a current environment and opened a PR that fixes it
along with the follow-on breakages that appear once the toolbar import is
corrected: https://github.com/Dih5/xpecgen/pull/20

The `NavigationToolbar2TkAgg` → `NavigationToolbar2Tk` rename was only the
first error. On a modern stack the GUI and calculation also hit:

- `FigureCanvasTkAgg.show()` was removed → use `draw()`
- `Figure(facecolor="SystemButtonFace")` — matplotlib no longer accepts the
  Tk color name (`ValueError: Invalid RGBA argument: 'SystemButtonFace'`)
- a missing `import sys` in the matplotlib-embedding fallback
- `scipy.integrate.simps` was renamed to `simpson` (removed in SciPy 1.14)
- the source-function integrand returns a 1×1 array, which `scipy.quad` can
  no longer coerce to a scalar under NumPy ≥ 1.25/2.0
  (`TypeError: only 0-dimensional arrays can be converted to Python scalars`)

@Dih5 — regarding the matplotlib bug (#12074) you mentioned as the reason
for not merging b751995: I could not reproduce it here. The GUI launches
and renders the plot normally. My tested environment:

- Windows 11, Python 3.13
- matplotlib 3.10.9, scipy 1.17.1, numpy 2.4.6, XlsxWriter 3.2.9

The PR uses a backwards-compatible import for `simpson`/`simps` and
`np.asarray(...).item()` for the scalar conversion, so it should work on
both old and new dependency versions. Happy to adjust anything if you'd
like to get this onto the main branch.

**Comment by Dih5** [comment]
@fleusium: Thank you for preparing the fix. It works perfectly in my current environment as well, so I have updated the PyPI distribution as well.

@ericpace: Please accept my apologies for missing your message. It's likely too late to give a relevant answer now, but I wanted to apologize for the oversight.
